export enum PermissionEnum {
    CREATE_USER = "CREATE_USER",
    READ_USER = "READ_USER",
    UPDATE_USER = "UPDATE_USER",
    DELETE_USER = "DELETE_USER",

    CREATE_POST = "CREATE_POST",
    READ_POST = "READ_POST",
    READ_ALL_POSTS = "READ_ALL_POSTS",
    UPDATE_POST = "UPDATE_POST",
    DELETE_POST = "DELETE_POST",

    CREATE_CATEGORY = "CREATE_CATEGORY",
    READ_CATEGORY = "READ_CATEGORY",
    READ_ALL_CATEGORIES = "READ_ALL_CATEGORIES",
    UPDATE_CATEGORY = "UPDATE_CATEGORY",
    DELETE_CATEGORY = "DELETE_CATEGORY",

    CREATE_COMMENT = "CREATE_COMMENT",
    READ_COMMENT = "READ_COMMENT",
    UPDATE_COMMENT = "UPDATE_COMMENT",
    DELETE_COMMENT = "DELETE_COMMENT",

    READ_ROLE = "READ_ROLE",
    UPDATE_ROLE = "UPDATE_ROLE",

    READ_PROFILE = "READ_PROFILE",
    UPDATE_PROFILE = "UPDATE_PROFILE",
}